name: Terraform checks

on: [pull_request]

jobs:
  build:
    name: lint, install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3.1.1
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true
      - name: Terraform Validate
        id: validate
        run:
          - cd example
          - terraform init -backend=false
          - terraform validate -no-color
          - terraform fmt --check
